name: cbshow auto update

on:
  workflow_dispatch:  # 手動觸發

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: 下載程式碼
        uses: actions/checkout@v3

      - name: 安裝 Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: 執行腳本
        run: python auto_update.py
